spring.application.name=guardian-plus-platform

# Default to development when no explicit profile is provided
spring.profiles.default=${SPRING_PROFILES_ACTIVE:dev}

# Shared Spring DataSource Configuration
spring.datasource.driver-class-name=org.postgresql.Driver

# Shared Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.naming.physical-strategy=com.healthify.guardian.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategyspring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Application Information for Documentation
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# i18n message bundles
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Flyway Configuration
spring.flyway.enabled=false