package com.healthify.guardian.platform.careroutineswellness.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of an {@code ActivityMonitor} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record ActivityMonitorId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "activity-monitor.id.invalid";

    public ActivityMonitorId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier for an activity monitor being created.
     */
    public static ActivityMonitorId generate() {
        return new ActivityMonitorId(UUID.randomUUID());
    }
}
