package com.healthify.guardian.platform.careroutineswellness.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of an {@code ActivityLogEntry} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record ActivityLogEntryId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "activity-log-entry.id.invalid";

    public ActivityLogEntryId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier for an activity log entry being created.
     */
    public static ActivityLogEntryId generate() {
        return new ActivityLogEntryId(UUID.randomUUID());
    }
}
