package com.healthify.guardian.platform.careroutineswellness.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of a {@code HydrationPlan} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record HydrationPlanId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "hydration-plan.id.invalid";

    public HydrationPlanId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier for a hydration plan being created.
     */
    public static HydrationPlanId generate() {
        return new HydrationPlanId(UUID.randomUUID());
    }
}
