package com.healthify.guardian.platform.careroutineswellness.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of a {@code MedicationStock} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record MedicationStockId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "medication-stock.id.invalid";

    public MedicationStockId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier for a medication stock being created.
     */
    public static MedicationStockId generate() {
        return new MedicationStockId(UUID.randomUUID());
    }
}
