package com.healthify.guardian.platform.careroutineswellness.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of a {@code Reminder} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record ReminderId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "reminder.id.invalid";

    public ReminderId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier for a reminder being created.
     */
    public static ReminderId generate() {
        return new ReminderId(UUID.randomUUID());
    }
}
