package com.healthify.guardian.platform.careroutineswellness.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of a {@code SleepCycleRecord} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record SleepCycleRecordId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "sleep-cycle-record.id.invalid";

    public SleepCycleRecordId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier for a sleep cycle record being created.
     */
    public static SleepCycleRecordId generate() {
        return new SleepCycleRecordId(UUID.randomUUID());
    }
}
