package com.healthify.guardian.platform.profile.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of a {@code CareRelationship} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record CareRelationshipId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "care-relationship.id.invalid";

    public CareRelationshipId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier.
     */
    public static CareRelationshipId generate() {
        return new CareRelationshipId(UUID.randomUUID());
    }
}