package com.healthify.guardian.platform.profile.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of a {@code CareRecipientProfile} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record CareRecipientProfileId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "care-recipient-profile.id.invalid";

    public CareRecipientProfileId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier.
     */
    public static CareRecipientProfileId generate() {
        return new CareRecipientProfileId(UUID.randomUUID());
    }
}