package com.healthify.guardian.platform.profile.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of a {@code UserProfile} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record UserProfileId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "user-profile.id.invalid";

    public UserProfileId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier.
     */
    public static UserProfileId generate() {
        return new UserProfileId(UUID.randomUUID());
    }
}