package com.healthify.guardian.platform.emergencyalerting.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of an {@code AlertDelivery} entity.
 *
 * @param value the underlying UUID; generated by the entity itself at creation time
 */
public record AlertDeliveryId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "alert-delivery.id.invalid";

    public AlertDeliveryId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier.
     */
    public static AlertDeliveryId generate() {
        return new AlertDeliveryId(UUID.randomUUID());
    }
}
