package com.healthify.guardian.platform.emergencyalerting.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of an {@code AlertSettings} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record AlertSettingsId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "alert-settings.id.invalid";

    public AlertSettingsId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier.
     */
    public static AlertSettingsId generate() {
        return new AlertSettingsId(UUID.randomUUID());
    }
}
