package com.healthify.guardian.platform.emergencyalerting.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of an {@code AlertResponse} entity.
 *
 * @param value the underlying UUID; generated by the entity itself at creation time
 */
public record AlertResponseId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "alert-response.id.invalid";

    public AlertResponseId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier.
     */
    public static AlertResponseId generate() {
        return new AlertResponseId(UUID.randomUUID());
    }
}
