package com.healthify.guardian.platform.emergencyalerting.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of an {@code Alert} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record AlertId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "alert.id.invalid";

    public AlertId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier.
     */
    public static AlertId generate() {
        return new AlertId(UUID.randomUUID());
    }
}
