package com.healthify.guardian.platform.emergencyalerting.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of an {@code AlertChannelSetting} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record AlertChannelSettingId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "alert-channel-setting.id.invalid";

    public AlertChannelSettingId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier.
     */
    public static AlertChannelSettingId generate() {
        return new AlertChannelSettingId(UUID.randomUUID());
    }
}
