package com.healthify.guardian.platform.emergencyalerting.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of an {@code EmergencyContact} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record EmergencyContactId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "emergency-contact.id.invalid";

    public EmergencyContactId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier.
     */
    public static EmergencyContactId generate() {
        return new EmergencyContactId(UUID.randomUUID());
    }
}
