package com.healthify.guardian.platform.emergencyalerting.domain.model.valueobjects;

import java.util.UUID;

/**
 * Immutable identifier of an {@code Incident} aggregate.
 *
 * @param value the underlying UUID; generated by the aggregate itself at creation time
 */
public record IncidentId(UUID value) {

    private static final String INVALID_MESSAGE_KEY = "incident.id.invalid";

    public IncidentId {
        if (value == null) {
            throw new IllegalArgumentException(INVALID_MESSAGE_KEY);
        }
    }

    /**
     * Generates a brand-new, random identifier.
     */
    public static IncidentId generate() {
        return new IncidentId(UUID.randomUUID());
    }
}
