package com.healthify.guardian.platform.emergencyalerting.application.internal.eventhandlers;

import com.healthify.guardian.platform.emergencyalerting.application.internal.outboundservices.AlertNotificationSender;
import com.healthify.guardian.platform.emergencyalerting.domain.model.events.AlertDispatchedEvent;
import com.healthify.guardian.platform.emergencyalerting.domain.model.valueobjects.Severity;
import com.healthify.guardian.platform.emergencyalerting.interfaces.events.EmergencyDispatchedIntegrationEvent;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Service;

/**
 * Sends the deliveries generated by every dispatch, escalation or broadcast (asynchronously,
 * through {@link AlertNotificationSender}), and republishes the first dispatch of a {@code CRITICAL}
 * or {@code HIGH} alert as an {@link EmergencyDispatchedIntegrationEvent} for other bounded contexts.
 */
@Service
public class AlertDispatchedEventHandler {

    private final AlertNotificationSender alertNotificationSender;
    private final ApplicationEventPublisher eventPublisher;

    public AlertDispatchedEventHandler(
            AlertNotificationSender alertNotificationSender, ApplicationEventPublisher eventPublisher) {
        this.alertNotificationSender = alertNotificationSender;
        this.eventPublisher = eventPublisher;
    }

    @EventListener
    public void on(AlertDispatchedEvent event) {
        alertNotificationSender.sendDeliveries(event.alertId(), event.deliveryIds());

        if (!event.initialDispatch() || event.severity() == Severity.MEDIUM) {
            return;
        }
        eventPublisher.publishEvent(new EmergencyDispatchedIntegrationEvent(
                event.alertId().value(),
                event.careRecipientProfileId().value(),
                event.sourceType().name(),
                event.severity().name(),
                event.dispatchedAt()));
    }
}
